### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/QuickChar#1]
Need to so put source files under a src folder + meson build

Likely we will git submodule this eventually into budgie-extras once we figure out how to do the keyboard launch without needing manually creating a keyboard shortcut

**Comment by Jacob-Vlijm** [comment]
Not sure what to do with the chardata file. Was thinking of also making it copy locally, so user can possibly override or add own characters. What do you mean by "once we figure out how to do the keyboard launch without needing manually creating a keyboard shortcut"?  Didn' t we figure that out?

**Comment by fossfreedom** [comment]
Closing.  Completed and git submodule linked to the extras repo
